### ISSUE TITLE
Support for analysis of self-generated binaries.

### ISSUE THREAD

**Issue by shivam-bathla** [pietroborrello/RopMate#1]
Hi,
     Great work guys! I really appreciate your efforts and the work you have done. Just wanted to know when would the support for analyzing self-generated binaries would be added. If not that, then if possible, probably the way to generate those JSON files would also be a lot of help.

Thanks.

**Comment by pietroborrello** [comment]
Hi, we are currently about to resume our work on ROPMate adding new features, so we will be releasing that part too in a few weeks. Stay tuned :)

**Comment by shivam-bathla** [comment]
Thanks for a quick reply. Yes, I am very keen to try it with my own binaries. Really great stuff.
Could you notify me on this thread once those parts are released as well? That would be really great.

Thanks.

**Comment by atlas0fd00m** [comment]
hey guys,

this looks like it could be a cool tool.
is the backend/analysis part going to be available soon?  currently i see a very pretty gui, but it's not helpful without the full package :)

thanks!
@

**Comment by pietroborrello** [comment]
Hi!
The back-end ended up being part of a bigger project, but I think it just makes more sense for me to release the backend at the state it was at the time of publication, so people can actually use this tool. 
I hope I'll publish it by the end of the month, I just have to find the time to document it a bit :)
Feel free to ping me here!

**Comment by pietroborrello** [comment]
[`RopDaemon`](https://github.com/pietroborrello/RopDaemon) is now open source! Using this tool you can generate custom databases for your own binaries :)
Install it with:

``` shell
$ git clone https://github.com/pietroborrello/RopDaemon
$ cd RopDaemon
$ python3 setup.py install
```
Generate the JSON database with:

``` shell
$ ropd -cvj <binary>
```
It will create a `<binary>.json` file that can be loaded in RopMate.
